// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptFileTransfer(arg1:string):Promise<void>;

export function Connect(arg1:number):Promise<void>;

export function ConnectCustom(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DeclineFileTransfer(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<main.AppConfig>;

export function GetCurrentRoom():Promise<string>;

export function GetUsername():Promise<string>;

export function InitiateFileTransfer(arg1:string,arg2:string):Promise<void>;

export function IsConnected():Promise<boolean>;

export function JoinRoom(arg1:string,arg2:string):Promise<void>;

export function LeaveRoom(arg1:string):Promise<void>;

export function ListRooms():Promise<void>;

export function ListUsers():Promise<void>;

export function OpenDownloadDir():Promise<void>;

export function PickFile():Promise<string>;

export function RequestMemberList(arg1:string):Promise<void>;

export function RequestRoomList():Promise<void>;

export function RequestUserList():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SendCommand(arg1:string):Promise<void>;

export function SendDM(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetCurrentRoom(arg1:string):Promise<void>;
