// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFileTransfer(arg1) {
  return window['go']['main']['App']['AcceptFileTransfer'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectCustom(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectCustom'](arg1, arg2, arg3, arg4);
}

export function DeclineFileTransfer(arg1) {
  return window['go']['main']['App']['DeclineFileTransfer'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentRoom() {
  return window['go']['main']['App']['GetCurrentRoom']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function InitiateFileTransfer(arg1, arg2) {
  return window['go']['main']['App']['InitiateFileTransfer'](arg1, arg2);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function JoinRoom(arg1, arg2) {
  return window['go']['main']['App']['JoinRoom'](arg1, arg2);
}

export function LeaveRoom(arg1) {
  return window['go']['main']['App']['LeaveRoom'](arg1);
}

export function ListRooms() {
  return window['go']['main']['App']['ListRooms']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function OpenDownloadDir() {
  return window['go']['main']['App']['OpenDownloadDir']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function RequestMemberList(arg1) {
  return window['go']['main']['App']['RequestMemberList'](arg1);
}

export function RequestRoomList() {
  return window['go']['main']['App']['RequestRoomList']();
}

export function RequestUserList() {
  return window['go']['main']['App']['RequestUserList']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SendDM(arg1, arg2) {
  return window['go']['main']['App']['SendDM'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetCurrentRoom(arg1) {
  return window['go']['main']['App']['SetCurrentRoom'](arg1);
}
